set fileencodings=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936
set termencoding=utf-8
set encoding=utf-8
set tabstop=4
set shiftwidth=4
set expandtab
set nu!
filetype on
set history=1000
set background=dark
set autoindent
set cindent
set smartindent
set ai!
set showmatch
set ruler
set nohls
set incsearch
set backspace=2
